// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfWzuT7JM_9882dxgOEDMvXx8CqzChoG4',
    appId: '1:1036503017632:web:ed78a6c1b4b33ddf8841c5',
    messagingSenderId: '1036503017632',
    projectId: 'weather-a9d2e',
    authDomain: 'weather-a9d2e.firebaseapp.com',
    storageBucket: 'weather-a9d2e.firebasestorage.app',
    measurementId: 'G-Y7EZ6L685J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6yntCuExFMecuiS8AEMBoaVLxtZj2F98',
    appId: '1:1036503017632:android:82fd3040cd300fe78841c5',
    messagingSenderId: '1036503017632',
    projectId: 'weather-a9d2e',
    storageBucket: 'weather-a9d2e.firebasestorage.app',
  );
}
